openapi: 3.1.0
info:
  title: Automox Policy Results API
  description: OpenAPI definition for the Automox Policy Results API
  version: v0
  contact:
    name: Automox Support
    url: https://help.automox.com/hc/en-us/requests/new
    email: support@automox.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://policyreport.automox.com
    description: Policy Report Service
security:
  - bearerAuth: []
tags:
  - name: Policy Runs
    description: Actions for Policy Runs Controller
  - name: Run Results
    description: Actions for Run Results Controller
  - name: Policy Count
    description: Actions for Policy Count
  - name: Policy Index
    description: Actions for Policy Index Controller
paths:
  /policy-history/policy-runs:
    get:
      tags:
        - Policy Runs
      summary: All Policy Executions
      description: |-
        Retrieve all policy executions for an organization *
        **See [Using Global API Keys](https://developer.automox.com/developer-portal/api-permission-scopes/#permissions-and-scopes) for more information on permission and scope requirements.**
      operationId: allPolicyExecutions
      deprecated: true
      parameters:
        - name: org
          in: query
          description: Organization UUID
          required: true
          schema:
            type: string
            format: uuid
            example: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
        - name: start_time
          in: query
          description: |
            "Beginning of desired Timeframe. Format: `start_time='2024-03-27T12:23:45Z'`"
          required: false
          schema:
            type: string
            example: '2024-03-27T12:23:45Z'
        - name: end_time
          in: query
          description: |
            "End of desired Timeframe. Format: `end_time='2023-04-27T12:23:45Z'`"
          required: false
          schema:
            type: string
            example: '2023-04-27T12:23:45Z'
        - name: policy_name
          in: query
          description: |
            'Filter by Policy Name. Format: `policy_name:in=patch,worklet`.
            Available operators: `equals`, `in`, `like`'
          required: false
          schema:
            type: string
            example: patch
        - name: policy_uuid
          in: query
          description: |
            'Filter by Policy UUID. Format: `policy_uuid:in=639b8c80-e0f3-418a-89e9-e6d9dfed36e7`.
            Available operators: `equals`, `in'
          required: false
          schema:
            type: string
            format: uuid
            example: 385f2dde-dfa9-427d-bbd5-8f7fd95af0e9
        - name: policy_type
          in: query
          description: |
            'Filter by Policy Types: `custom`, `patch`, `required_software`. Format:
            `policy_type:in=required_software,custom`. Available operators: `equals`, `in`'
          required: false
          schema:
            type: string
            example: required_software
        - name: result_status
          in: query
          description: |
            'Filter by Result Statuses: `success`, `failed`, `pending`, `not_applicable, not_included`.
            Format: `result_status:equals=success`. Available operators: `equals`, `in`'
          required: false
          schema:
            type: string
            example: success
        - name: sort
          in: query
          description: Sort by `device_count`, `run_time`, `policy_name`
          required: false
          schema:
            type: string
            description: Comma delimited list of sorts to apply
            readOnly: true
            default: run_time:desc
            example: policy_name:asc,run_time:desc
        - name: page
          in: query
          required: false
          description: |
            The page of results you wish to be returned with page numbers starting
            at 0. See [About Automox API - Pagination](/developer-portal#pagination)
          schema:
            type: integer
            format: int32
            example: 0
        - name: limit
          in: query
          description: Default is 25, max is 5000
          required: false
          schema:
            type: integer
            format: int32
            maximum: 5000
            default: 25
            example: 25
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionResponsePolicyRunsReportResource'
              examples:
                CollectionResponsePolicyRunsReportResource:
                  summary: Policy Runs Report Resource
                  value:
                    metadata:
                      current_page: 0
                      total_pages: 100
                      total_count: 1300
                      limit: 25
                      links:
                        previous: ''
                        next: policyreport.automox.com?page=1&limit=25
                    data:
                      - policy_uuid: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
                        policy_id: 123456
                        org_uuid: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
                        policy_name: Patch Tuesday
                        policy_type: patch
                        policy_deleted_at: '2024-03-27T12:23:45Z'
                        device_count: 100
                        pending: 10
                        success: 80
                        remediation_not_applicable: 5
                        failed: 5
                        run_time: '2024-03-27T12:23:45Z'
                        execution_token: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
                        run_count: 100
                        not_included: 5
        '400':
          description: Bad Request
          $ref: '#/components/responses/BadRequest'
        '401':
          description: Unauthorized
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: Unauthorized Action
          $ref: '#/components/responses/UnauthorizedAction'
        '404':
          description: Not Found
          $ref: '#/components/responses/NotFound'
        '408':
          description: Request Timeout
          $ref: '#/components/responses/RequestTimeout'
        '429':
          description: Rate Limit
          $ref: '#/components/responses/RateLimit'
        '500':
          description: Service Unavailable
          $ref: '#/components/responses/ServiceUnavailable'
  /policy-history/policy-runs/{policy_uuid}:
    get:
      tags:
        - Policy Runs
      summary: Policy Executions per Policy
      description: |-
        Retrieve all policy executions for a policy 
        **See [Using Global API Keys](https://developer.automox.com/developer-portal/api-permission-scopes/#permissions-and-scopes) for more information on permission and scope requirements.**
      operationId: executionsByPolicy
      deprecated: true
      parameters:
        - name: org
          in: query
          description: Organization UUID
          required: true
          schema:
            type: string
            format: uuid
            example: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
        - name: policy_uuid
          in: path
          description: Policy UUID
          required: true
          schema:
            type: string
            format: uuid
            example: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
        - name: report_days
          in: query
          description: Number of Days Before Today's Date
          required: false
          schema:
            type: integer
            format: int32
            default: 7
            example: 7
        - name: sort
          in: query
          description: Sort by `run_time`
          required: false
          schema:
            type: string
            description: Comma delimited list of sorts to apply
            example: run_time:asc
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RunsByPolicyResponse'
              examples:
                RunsByPolicyResponse:
                  summary: Runs By Policy Response
                  value:
                    data:
                      runs:
                        - policy_uuid: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
                          policy_id: 123456
                          org_uuid: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
                          policy_name: Patch Tuesday
                          policy_type: patch
                          policy_deleted_at: '2024-03-27T12:23:45Z'
                          device_count: 100
                          pending: 10
                          success: 80
                          remediation_not_applicable: 5
                          failed: 5
                          run_time: '2024-03-27T12:23:45Z'
                          execution_token: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
                          run_count: 100
                          not_included: 5
                      banner_stats:
                        policy_success_rate: 95.5
                        total_policies_applied: 100
                        total_successful_devices: 95
                    metadata:
                      total_run_count: 100
                      last_run_time: '2024-03-27T12:23:45Z'
        '400':
          description: Bad Request
          $ref: '#/components/responses/BadRequest'
        '401':
          description: Unauthorized
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: Unauthorized Action
          $ref: '#/components/responses/UnauthorizedAction'
        '404':
          description: Not Found
          $ref: '#/components/responses/NotFound'
        '408':
          description: Request Timeout
          $ref: '#/components/responses/RequestTimeout'
        '429':
          description: Rate Limit
          $ref: '#/components/responses/RateLimit'
        '500':
          description: Service Unavailable
          $ref: '#/components/responses/ServiceUnavailable'
  /policy-history/policies/{policy_uuid}/{exec_token}:
    get:
      tags:
        - Run Results
      summary: Device policy run results
      description: |-
        Retrieve the results of a policy at the device level for a given execution token 
        **See [Using Global API Keys](https://developer.automox.com/developer-portal/api-permission-scopes/#permissions-and-scopes) for more information on permission and scope requirements.**
      operationId: policyDeviceDetail
      deprecated: true
      parameters:
        - name: policy_uuid
          in: path
          description: Policy UUID
          required: true
          schema:
            type: string
            format: uuid
            example: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
        - name: exec_token
          in: path
          description: Execution Token
          required: true
          schema:
            type: string
            format: uuid
            example: 10af9475-fd20-4189-bb9c-e1c707ff2670
        - name: org
          in: query
          description: Organization UUID
          required: true
          schema:
            type: string
            format: uuid
            example: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
        - name: sort
          in: query
          description: Sort by `run_time`, `device_display_name`, or `result_status`
          required: false
          schema:
            type: string
            description: Comma delimited list of sorts to apply
            examples:
              - run_time:asc
        - name: result_status
          in: query
          description: 'Filter by Policy run result: `applied`, `failed`, `pending`, not_applicable, not_included. Format: `result_status:in[]=applied`. Available operators: `equals`, `in`'
          required: false
          schema:
            type: string
            example: applied
        - name: device_name
          in: query
          description: 'Filter by the device name. This will search both device hostname and custom name.Format: `device_name:like=WIN-RM1OMA6IBCA`'
          required: false
          schema:
            type: string
            example: Marcus' Macbook Pro
        - name: page
          in: query
          required: false
          description: The page of results you wish to be returned with page numbers starting at 0. See [About Automox API - Pagination](/developer-portal#pagination)
          schema:
            type: integer
            format: int32
            example: 0
        - name: limit
          in: query
          description: Default is 25, max is 5000
          required: false
          schema:
            type: integer
            format: int32
            maximum: 5000
            default: 25
            example: 25
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionResponseDeviceDetailsResource'
              examples:
                CollectionResponseDeviceDetailsResource:
                  summary: Collection Response Device Details Resource
                  value:
                    metadata:
                      current_page: 0
                      total_pages: 100
                      total_count: 1300
                      limit: 25
                      links:
                        previous: ''
                        next: policyreport.automox.com?page=1&limit=25
                    data:
                      - device_id: 250624
                        device_uuid: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
                        hostname: WIN-RM1OMA6IBCA
                        custom_name: Marcus' Macbook Pro
                        display_name: Marcus' Macbook Pro
                        result_status: success
                        result-reason: ''
                        run_time: '2024-03-27T12:23:45Z'
                        event_time: '2024-03-27T12:23:45Z'
                        patches:
                          - KB123456
                          - KB234567
                        stdout: |
                          Successfully installed KB123456
                          Successfully installed KB234567
                        stderr: ''
                        error_code: 1
                        device_deleted_at: '2024-03-27T12:23:45Z'
                        policy_uuid: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
                        policy_name: Patch Tuesday
                        policy_type: patch
        '400':
          description: Bad Request
          $ref: '#/components/responses/BadRequest'
        '401':
          description: Unauthorized
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: Unauthorized Action
          $ref: '#/components/responses/UnauthorizedAction'
        '404':
          description: Not Found
          $ref: '#/components/responses/NotFound'
        '408':
          description: Request Timeout
          $ref: '#/components/responses/RequestTimeout'
        '429':
          description: Rate Limit
          $ref: '#/components/responses/RateLimit'
        '500':
          description: Service Unavailable
          $ref: '#/components/responses/ServiceUnavailable'
  /policy-history/policy-run-count:
    get:
      tags:
        - Policy Count
      summary: Policy Run Count
      description: |-
        Retrieve the total number of polices executed in the given number of days 
        **See [Using Global API Keys](https://developer.automox.com/developer-portal/api-permission-scopes/#permissions-and-scopes) for more information on permission and scope requirements.**
      operationId: policyIndex
      deprecated: true
      parameters:
        - name: org
          in: query
          description: Organization UUID
          required: true
          schema:
            type: string
            format: uuid
            example: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
        - name: days
          in: query
          description: Amount of days after today's date
          required: false
          schema:
            type: integer
            format: int32
            default: 7
            example: 7
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PolicyRunCount'
              examples:
                PolicyRunCount:
                  summary: Policy Run Count
                  value:
                    policy_runs: 100
        '400':
          description: Bad Request
          $ref: '#/components/responses/BadRequest'
        '401':
          description: Unauthorized
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: Unauthorized Action
          $ref: '#/components/responses/UnauthorizedAction'
        '404':
          description: Not Found
          $ref: '#/components/responses/NotFound'
        '408':
          description: Request Timeout
          $ref: '#/components/responses/RequestTimeout'
        '429':
          description: Rate Limit
          $ref: '#/components/responses/RateLimit'
        '500':
          description: Service Unavailable
          $ref: '#/components/responses/ServiceUnavailable'
  /policy-history/policies:
    get:
      tags:
        - Policy Index
      summary: Policy Execution Counts
      description: |-
        Retrieve all policy execution counts 
        **See [Using Global API Keys](https://developer.automox.com/developer-portal/api-permission-scopes/#permissions-and-scopes) for more information on permission and scope requirements.**
      operationId: policyIndexCount
      deprecated: true
      parameters:
        - name: org
          in: query
          description: Organization UUID
          required: true
          schema:
            type: string
            format: uuid
            example: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
        - name: start_time
          in: query
          description: The date-time the policy execution started
          required: false
          schema:
            type: string
            default: ''
            example: '2024-03-27T12:23:45Z'
        - name: end_time
          in: query
          description: The date-time that the policy execution ended
          required: false
          schema:
            type: string
            default: ''
            example: '2023-04-27T12:23:45Z'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PolicyRunsResponse'
              examples:
                PolicyRunsResponse:
                  summary: Policy Runs Response
                  value:
                    data:
                      - org_uuid: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
                        policy_id: 123456
                        policy_name: Patch Tuesday
                        policy_uuid: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
                        exec_time: '2024-03-27T12:23:45Z'
                        run_count: 100
        '400':
          description: Bad Request
          $ref: '#/components/responses/BadRequest'
        '401':
          description: Unauthorized
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: Unauthorized Action
          $ref: '#/components/responses/UnauthorizedAction'
        '404':
          description: Not Found
          $ref: '#/components/responses/NotFound'
        '408':
          description: Request Timeout
          $ref: '#/components/responses/RequestTimeout'
        '429':
          description: Rate Limit
          $ref: '#/components/responses/RateLimit'
        '500':
          description: Service Unavailable
          $ref: '#/components/responses/ServiceUnavailable'
  /policy-history/policies/{policy_uuid}:
    get:
      tags:
        - Policy Index
      summary: Policy Information
      description: |-
        Retrieve the policy information for a given policy UUID 
        **See [Using Global API Keys](https://developer.automox.com/developer-portal/api-permission-scopes/#permissions-and-scopes) for more information on permission and scope requirements.**
      operationId: policyInformation
      deprecated: true
      parameters:
        - name: policy_uuid
          in: path
          description: Policy UUID
          required: true
          schema:
            type: string
            format: uuid
            example: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
        - name: org
          in: query
          description: Organization UUID
          required: true
          schema:
            type: string
            format: uuid
            example: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PolicyInfoResource'
              examples:
                PolicyInfoResource:
                  summary: Policy Info Resource
                  value:
                    uuid: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
                    id: 123456
                    org_uuid: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
                    name: Patch Tuesday
                    type: patch
                    deleted_at: '2024-03-27T12:23:45Z'
                    updated_at: '2024-03-27T12:23:45Z'
                    last_run_time: '2024-03-27T12:23:45Z'
        '400':
          description: Bad Request
          $ref: '#/components/responses/BadRequest'
        '401':
          description: Unauthorized
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: Unauthorized Action
          $ref: '#/components/responses/UnauthorizedAction'
        '404':
          description: Not Found
          $ref: '#/components/responses/NotFound'
        '408':
          description: Request Timeout
          $ref: '#/components/responses/RequestTimeout'
        '429':
          description: Rate Limit
          $ref: '#/components/responses/RateLimit'
        '500':
          description: Service Unavailable
          $ref: '#/components/responses/ServiceUnavailable'
  /policy-history/policies/{policy_uuid}/runs:
    get:
      tags:
        - Policy Index
      summary: Execution History for a Policy
      description: |-
        Retrieve the execution history for a policy 
        **See [Using Global API Keys](https://developer.automox.com/developer-portal/api-permission-scopes/#permissions-and-scopes) for more information on permission and scope requirements.**
      operationId: policyExecutionHistory
      deprecated: true
      parameters:
        - name: policy_uuid
          in: path
          description: Policy UUID
          required: true
          schema:
            type: string
            format: uuid
            example: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
        - name: org
          in: query
          description: Organization UUID
          required: true
          schema:
            type: string
            format: uuid
            example: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PolicyAllRunsListResponse'
              examples:
                PolicyAllRunsListResponse:
                  summary: Policy All Runs List Response
                  value:
                    data:
                      - policy_id: 123456
                        policy_uuid: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
                        run_time: 2024-03-27T12:23Z
                        execution_token: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
        '400':
          description: Bad Request
          $ref: '#/components/responses/BadRequest'
        '401':
          description: Unauthorized
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: Unauthorized Action
          $ref: '#/components/responses/UnauthorizedAction'
        '404':
          description: Not Found
          $ref: '#/components/responses/NotFound'
        '408':
          description: Request Timeout
          $ref: '#/components/responses/RequestTimeout'
        '429':
          description: Rate Limit
          $ref: '#/components/responses/RateLimit'
        '500':
          description: Service Unavailable
          $ref: '#/components/responses/ServiceUnavailable'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    CollectionMetaDataLinks:
      description: Metadata links for pagination
      type: object
      properties:
        previous:
          type: string
          description: Previous Pages URL
          examples:
            - policyreport.automox.com?page=1&limit=25
        next:
          type: string
          description: Next Pages URL
          examples:
            - policyreport.automox.com?page=1&limit=25
      examples:
        - previous: policyreport.automox.com?page=0&limit=25
          next: policyreport.automox.com?page=1&limit=25
    CollectionMetaData:
      type: object
      description: Collection Metadata
      properties:
        current_page:
          type: integer
          description: Current Page
          format: int32
          examples:
            - 1
        total_pages:
          type: integer
          description: Total Pages
          format: int32
          examples:
            - 100
        total_count:
          type: integer
          description: Total Record Count
          format: int64
          examples:
            - 1300
        limit:
          type: integer
          description: Limit of Records Per Page
          format: int32
          examples:
            - 25
        links:
          $ref: '#/components/schemas/CollectionMetaDataLinks'
      example:
        current_page: 0
        total_pages: 100
        total_count: 1300
        limit: 25
        links:
          previous: ''
          next: policyreport.automox.com?page=1&limit=25
    PolicyRunsReportResource:
      type: object
      description: Policy Runs Report Resource
      properties:
        policy_uuid:
          type: string
          format: uuid
          examples:
            - 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
        policy_id:
          type: integer
          format: int64
          examples:
            - 123456
        org_uuid:
          type: string
          format: uuid
          examples:
            - 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
        policy_name:
          type: string
          examples:
            - Patch Tuesday
        policy_type:
          type: string
          examples:
            - patch
        policy_deleted_at:
          type: string
          format: date-time
          examples:
            - '2024-03-27T12:23:45Z'
        device_count:
          type: integer
          format: int32
          examples:
            - 100
        pending:
          type: integer
          format: int32
          examples:
            - 10
        success:
          type: integer
          format: int32
          examples:
            - 80
        remediation_not_applicable:
          type: integer
          format: int32
          examples:
            - 5
        failed:
          type: integer
          format: int32
          examples:
            - 5
        run_time:
          type: string
          format: date-time
          examples:
            - '2024-03-27T12:23:45Z'
        execution_token:
          type: string
          format: uuid
          examples:
            - 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
        run_count:
          type: integer
          format: int32
          examples:
            - 100
        not_included:
          type: integer
          format: int32
          examples:
            - 5
      example:
        policy_uuid: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
        policy_id: 123456
        org_uuid: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
        policy_name: Patch Tuesday
        policy_type: patch
        policy_deleted_at: '2024-03-27T12:23:45Z'
        device_count: 100
        pending: 10
        success: 80
        remediation_not_applicable: 5
        failed: 5
        run_time: '2024-03-27T12:23:45Z'
        execution_token: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
        run_count: 100
        not_included: 5
    CollectionResponsePolicyRunsReportResource:
      type: object
      description: Collection Response Policy Runs Report Resource
      properties:
        metadata:
          $ref: '#/components/schemas/CollectionMetaData'
        data:
          type: array
          items:
            $ref: '#/components/schemas/PolicyRunsReportResource'
      example:
        metadata:
          current_page: 0
          total_pages: 100
          total_count: 1300
          limit: 25
          links:
            previous: ''
            next: policyreport.automox.com?page=1&limit=25
        data:
          - policy_uuid: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
            policy_id: 123456
            org_uuid: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
            policy_name: Patch Tuesday
            policy_type: patch
            policy_deleted_at: '2024-03-27T12:23:45Z'
            device_count: 100
            pending: 10
            success: 80
            remediation_not_applicable: 5
            failed: 5
            run_time: '2024-03-27T12:23:45Z'
            execution_token: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
            run_count: 100
            not_included: 5
    ValidationError:
      type: object
      properties:
        field:
          type: string
          description: Request field with error
          examples:
            - fieldName
        errors:
          type: array
          description: List of errors encountered
          items:
            type: string
            description: List of errors encountered
            examples:
              - '["An error message"]'
      description: Validation errors
      example:
        field: fieldName
        errors:
          - An error message
    BannerStatsResource:
      type: object
      description: Banner Stats Resource
      properties:
        policy_success_rate:
          type: number
          format: double
          examples:
            - 95.5
        total_policies_applied:
          type: integer
          format: int32
          examples:
            - 100
        total_successful_devices:
          type: integer
          format: int32
          examples:
            - 95
      example:
        policy_success_rate: 95.5
        total_policies_applied: 100
        total_successful_devices: 95
    Data:
      type: object
      description: Data Object
      properties:
        runs:
          type: array
          items:
            $ref: '#/components/schemas/PolicyRunsReportResource'
        banner_stats:
          $ref: '#/components/schemas/BannerStatsResource'
      example:
        runs:
          - policy_uuid: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
            policy_id: 123456
            org_uuid: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
            policy_name: Patch Tuesday
            policy_type: patch
            policy_deleted_at: '2024-03-27T12:23:45Z'
            device_count: 100
            pending: 10
            success: 80
            remediation_not_applicable: 5
            failed: 5
            run_time: '2024-03-27T12:23:45Z'
            execution_token: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
            run_count: 100
            not_included: 5
        banner_stats:
          policy_success_rate: 95.5
          total_policies_applied: 100
          total_successful_devices: 95
    Metadata:
      type: object
      description: Metadata Object
      properties:
        total_run_count:
          type: integer
          format: int32
          examples:
            - 100
        last_run_time:
          type: string
          format: date-time
          examples:
            - '2024-03-27T12:23:45Z'
      example:
        total_run_count: 100
        last_run_time: '2024-03-27T12:23:45Z'
    RunsByPolicyResponse:
      description: Policy Runs by Policy
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Data'
        metadata:
          $ref: '#/components/schemas/Metadata'
      example:
        data:
          runs:
            - policy_uuid: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
              policy_id: 123456
              org_uuid: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
              policy_name: Patch Tuesday
              policy_type: patch
              policy_deleted_at: '2024-03-27T12:23:45Z'
              device_count: 100
              pending: 10
              success: 80
              remediation_not_applicable: 5
              failed: 5
              run_time: '2024-03-27T12:23:45Z'
              execution_token: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
              run_count: 100
              not_included: 5
          banner_stats:
            policy_success_rate: 95.5
            total_policies_applied: 100
            total_successful_devices: 95
        metadata:
          total_run_count: 100
          last_run_time: '2024-03-27T12:23:45Z'
    DeviceDetailsResource:
      type: object
      description: Device Policy Run Details
      properties:
        device_id:
          type: integer
          format: int64
          examples:
            - 250624
        device_uuid:
          type: string
          format: uuid
          examples:
            - 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
        hostname:
          type: string
          examples:
            - WIN-RM1OMA6IBCA
        custom_name:
          type: string
          examples:
            - Marcus' Macbook Pro
        display_name:
          type: string
          examples:
            - Marcus' Macbook Pro
        result_status:
          type: string
          examples:
            - success
        result-reason:
          type: string
        run_time:
          type: string
          format: date-time
          examples:
            - '2024-03-27T12:23:45Z'
        event_time:
          type: string
          format: date-time
          examples:
            - '2024-03-27T12:23:45Z'
        patches:
          type: array
          items:
            type: string
        stdout:
          type: string
        stderr:
          type: string
        exit_code:
          type: integer
          format: int32
        device_deleted_at:
          type: string
          format: date-time
          examples:
            - '2024-03-27T12:23:45Z'
        policy_id:
          type: integer
          format: int64
          examples:
            - 123456
        policy_uuid:
          type: string
          format: uuid
          examples:
            - 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
        policy_name:
          type: string
          examples:
            - Patch Tuesday
        policy_type:
          type: string
          examples:
            - patch
      example:
        device_id: 250624
        device_uuid: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
        hostname: WIN-RM1OMA6IBCA
        custom_name: Marcus' Macbook Pro
        display_name: Marcus' Macbook Pro
        result_status: success
        result-reason: ''
        run_time: '2024-03-27T12:23:45Z'
        event_time: '2024-03-27T12:23:45Z'
        patches:
          - KB123456
          - KB234567
        stdout: |
          Successfully installed KB123456
          Successfully installed KB234567
        stderr: ''
        exit_code: 0
        device_deleted_at: '2024-03-27T12:23:45Z'
        policy_id: 123456
        policy_uuid: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
        policy_name: Patch Tuesday
        policy_type: patch
    CollectionResponseDeviceDetailsResource:
      type: object
      description: Collection Response Device Details
      properties:
        metadata:
          $ref: '#/components/schemas/CollectionMetaData'
        data:
          type: array
          items:
            $ref: '#/components/schemas/DeviceDetailsResource'
      example:
        metadata:
          current_page: 0
          total_pages: 100
          total_count: 1300
          limit: 25
          links:
            previous: ''
            next: policyreport.automox.com?page=1&limit=25
        data:
          - device_id: 250624
            device_uuid: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
            hostname: WIN-RM1OMA6IBCA
            custom_name: Marcus' Macbook Pro
            display_name: Marcus' Macbook Pro
            result_status: success
            result-reason: ''
            run_time: '2024-03-27T12:23:45Z'
            event_time: '2024-03-27T12:23:45Z'
            patches:
              - KB123456
              - KB234567
            stdout: |
              Successfully installed KB123456
              Successfully installed KB234567
            stderr: ''
            exit_code: 0
            device_deleted_at: '2024-03-27T12:23:45Z'
            policy_id: 123456
            policy_uuid: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
            policy_name: Patch Tuesday
            policy_type: patch
    PolicyRunCount:
      type: object
      description: Policy Run Count
      properties:
        policy_runs:
          type: integer
          format: int64
          examples:
            - 100
      example:
        policy_runs: 100
    PolicyExecutionWithRunCount:
      type: object
      description: Policy Execution with Run Count
      properties:
        org_uuid:
          type: string
          examples:
            - 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
        policy_id:
          type: integer
          format: int64
          examples:
            - 123456
        policy_name:
          type: string
          examples:
            - Patch Tuesday
        policy_uuid:
          type: string
          format: uuid
          examples:
            - 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
        exec_time:
          type: string
          format: date-time
          examples:
            - '2024-03-27T12:23:45Z'
        run_count:
          type: integer
          format: int64
          examples:
            - 100
      example:
        org_uuid: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
        policy_id: 123456
        policy_name: Patch Tuesday
        policy_uuid: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
        exec_time: '2024-03-27T12:23:45Z'
        run_count: 100
    PolicyRunsResponse:
      type: object
      description: Policy Runs Response
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/PolicyExecutionWithRunCount'
      example:
        data:
          - org_uuid: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
            policy_id: 123456
            policy_name: Patch Tuesday
            policy_uuid: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
            exec_time: '2024-03-27T12:23:45Z'
            run_count: 100
    PolicyInfoResource:
      type: object
      description: Policy Info Resource
      properties:
        id:
          type: integer
          format: int64
          examples:
            - 123456
        uuid:
          type: string
          format: uuid
          examples:
            - 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
        org_uuid:
          type: string
          format: uuid
          examples:
            - 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
        name:
          type: string
          examples:
            - Patch Tuesday
        type:
          type: string
          examples:
            - patch
        deleted_at:
          type: string
          format: date-time
          examples:
            - '2024-03-27T12:23:45Z'
        updated_at:
          type: string
          format: date-time
          examples:
            - '2024-03-27T12:23:45Z'
        last_run_time:
          type: string
          format: date-time
          examples:
            - '2024-03-27T12:23:45Z'
    ExecutionTokenAndRunTime:
      type: object
      description: Execution Token and Run Time
      properties:
        policy_id:
          type: integer
          format: int64
          examples:
            - 123456
        policy_uuid:
          type: string
          format: uuid
          examples:
            - 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
        run_time:
          type: string
          format: date-time
          examples:
            - '2024-03-27T12:23:45Z'
        execution_token:
          type: string
          format: uuid
          examples:
            - 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
      example:
        policy_id: 123456
        policy_uuid: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
        run_time: '2024-03-27T12:23:45Z'
        execution_token: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
    PolicyAllRunsListResponse:
      type: object
      description: Policy All Runs List Response
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/ExecutionTokenAndRunTime'
      example:
        data:
          - policy_id: 123456
            policy_uuid: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
            run_time: 2024-03-27T12:23Z
            execution_token: 56c0ba07-69f2-4f7c-b0a1-2bb0ed68578e
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            properties:
              status:
                type: integer
                description: HTTP Status Code
                format: int32
                examples:
                  - 400
              code:
                type: string
                description: Error code
                examples:
                  - error-type
              title:
                type: string
                description: Error title
                examples:
                  - Error Title
              message:
                type: string
                description: Error message
                examples:
                  - Error message
              stackTrace:
                type: array
                description: Stack trace
                items:
                  type: string
                  description: Stack trace
              errors:
                type: array
                description: Validation errors
                items:
                  $ref: '#/components/schemas/ValidationError'
    Unauthorized:
      description: Access token is missing or invalid
      content:
        application/json:
          schema:
            properties:
              errors:
                type: array
                maxItems: 1
                items:
                  type: string
            required:
              - errors
            example:
              errors:
                - Unauthorized
    UnauthorizedAction:
      description: You do not have permission to perform this action.
      content:
        application/json:
          schema:
            properties:
              errors:
                type: array
                items:
                  type: string
            required:
              - errors
    NotFound:
      description: Entity not found
      content:
        application/json:
          schema:
            properties:
              errors:
                type: array
                items:
                  type: string
                maxItems: 1
    RequestTimeout:
      description: The request has timed out.
      content:
        application/json:
          schema:
            properties:
              errors:
                type: array
                items:
                  type: string
            required:
              - errors
    RateLimit:
      description: Too many requests
      content:
        application/json:
          schema:
            properties:
              errors:
                type: array
                maxItems: 1
                items:
                  type: string
    ServiceUnavailable:
      description: Service Unavailable
      content:
        application/json:
          schema:
            properties:
              errors:
                type: array
                maxItems: 1
                items:
                  type: string
x-tagGroups:
  - name: Policy Results History
    tags:
      - Policy Runs
      - Run Results
      - Policy Count
      - Policy Index
